name: 'Dependency Review'
on:
  pull_request:
    branches: [ $default-branch ]

permissions:
  contents: read

jobs:
    dependency-Review:
      uses: coveo/public-actions/.github/workflows/dependency-review.yml@main
      with:
        public: false
        distributed: true