name: 'Dependency Review'

on:
  pull_request:
    branches: [ $default-branch, $protected-branches ]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-Review:
    name: Review
    uses: coveo/public-actions/.github/workflows/dependency-review.yml@main
    with:
      public: false
      distributed: true
