name: Snyk Code
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
    types: [opened, edited, synchronize, reopened]

jobs:
    Snyk-Code:
      runs-on: ubuntu-latest
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        # Fill out with the action suffix you need to run
        # e.g. for, node, just put 'node'.
        SNYK_ACTION_TYPE: ''
      steps:
        - name: Checkout code
          use: actions/checkout@v2
        - name: Run Snyk Code
          uses: snyk/actions/$SNYK_ACTION_TYPE@d1ee3d73c6f24375d0efc597c74570b0cd08a323
          command: code test
          # Fill out the args you need here. You need at least to specify your Snyk Organization.
          # args: --org=YOUR_SNYK_ORG